backend:
  name: github
  repo: <% GITHUB_REPOSITORY %> # Gulp will replace this with your GitHub repository
  branch: master # Branch to update (master by default)

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", default: ["post"]}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "announcements" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Announcement" # Used in the UI, ie.: "New Post"
    folder: "site/content/announcements" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", default: ["announcement"]}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "events" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Event" # Used in the UI, ie.: "New Post"
    folder: "site/content/events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", default: ["event"]}
      - {label: "Body", name: "body", widget: "markdown"}