baseURL = "http://beerjs.mk/"
languageCode = "mk"
title = "BeerJS MK"
theme = "beerjsmk"

[params]
  description = "A meetup for beer and javascript enthsiasts"
  name = "BeerJS"
[taxonomies]
  tag = "tags"
  category = "categories"