/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    fontFamily: {
      'system-ui': ['system-ui', 'sans-serif'],
      transitional: ['Charter', 'Bitstream Charter', 'Sitka Text', 'Cambria', 'serif'],
      'old-style': ['Iowan Old Style', 'Palatino Linotype', 'URW Palladio L', 'P052', 'serif'],
      humanist: ['Seravek', 'Gill Sans Nova', 'Ubuntu', 'Calibri', 'DejaVu Sans', 'source-sans-pro', 'sans-serif'],
      'geometric-humanist': [
        'Avenir',
        'Avenir Next LT Pro',
        'Montserrat',
        'Corbel',
        'URW Gothic',
        'source-sans-pro',
        'sans-serif',
      ],
      'classical-humanist': ['Optima', 'Candara', 'Noto Sans', 'source-sans-pro', 'sans-serif'],
      'neo-grotesque': ['Inter', 'Roboto', 'Helvetica Neue', 'Arial Nova', 'Nimbus Sans', 'Arial', 'sans-serif'],
      'monospace-slab-serif': ['Nimbus Mono PS', 'Courier New', 'Cutive Mono', 'monospace'],
      'monospace-code': [
        'ui-monospace',
        'Cascadia Code',
        'Source Code Pro',
        'Menlo',
        'Consolas',
        'DejaVu Sans Mono',
        'monospace',
      ],
      industrial: [
        'Bahnschrift',
        'DIN Alternate',
        'Franklin Gothic Medium',
        'Nimbus Sans Narrow',
        'sans-serif-condensed',
        'sans-serif',
      ],
      'rounded-sans': [
        'ui-rounded',
        'Hiragino Maru Gothic ProN',
        'Quicksand',
        'Comfortaa',
        'Manjari',
        'Arial Rounded MT Bold',
        'Calibri',
        'source-sans-pro',
        'sans-serif',
      ],
      'slab-serif': ['Rockwell', 'Rockwell Nova', 'Roboto Slab', 'DejaVu Serif', 'Sitka Small', 'serif'],
      antique: [
        'Superclarendon',
        'Bookman Old Style',
        'URW Bookman',
        'URW Bookman L',
        'Georgia Pro',
        'Georgia',
        'serif',
      ],
      didone: ['Didot', 'Bodoni MT', 'Noto Serif Display', 'URW Palladio L', 'P052', 'Sylfaen', 'serif'],
      handwritten: ['Segoe Print', 'Bradley Hand', 'Chilanka', 'TSCu_Comic', 'casual', 'cursive'],
    },
    extend: {
      colors: {
        primary: {
          50: '#fefcec',
          100: '#fef8d8',
          200: '#fcf1b1',
          300: '#fbea8b',
          400: '#f9e364',
          500: '#f8dc3d',
          600: '#c6b031',
          700: '#958425',
          800: '#635818',
          900: '#322c0c',
        },
        secondary: {
          50: '#ecf4fe',
          100: '#d9e9fc',
          200: '#b4d3f9',
          300: '#8ebef7',
          400: '#69a8f4',
          500: '#4392f1',
          600: '#3675c1',
          700: '#285891',
          800: '#1b3a60',
          900: '#0d1d30',
        },
        base: {
          50: '#eaeaea',
          100: '#d6d4d4',
          200: '#aca9aa',
          300: '#837e7f',
          400: '#595355',
          500: '#30282a',
          600: '#262022',
          700: '#1d1819',
          800: '#131011',
          900: '#0a0808',
        },
      },
    },
  },
  plugins: [require('@tailwindcss/typography'), require('tailwindcss-elevation')],
};
