name = "Beerjsmk"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.3"

[author]
  name = "Darko Bozhinovski"
  homepage = "blog.bozhinovski.me"
